# word.yml
--- 
words: test,test,test,test

--- 
spring: 
  profiles: subject

server: 
  port: 8081

words: Spring Cloud,Spring Cloud
  
--- 
spring: 
  profiles: verb

server: 
  port: 8082

words: Config,Config
  
--- 
spring: 
  profiles: object

server: 
  port: 8083

words: works,works


